### ISSUE TITLE
State Role "Return" needed to be added to StateRoleEnum

### ISSUE THREAD

**Issue by SergeyKovalchuk** [labd/commercetools-go-sdk#44]
This is needed to be fixed to allow creation of Order/LineItem states with "Return" State role.
Unfortunately, I can not publish any PR to this repository.

Would be great to add this changes to 'types_state.go'
```
const (
	StateRoleEnumReviewIncludedInStatistics StateRoleEnum = "ReviewIncludedInStatistics"
	+ StateRoleEnumReturn StateRoleEnum = "Return" // There was no return type
)
```

Thanks a lot in advance 😃 

PS: I'm using https://github.com/labd/terraform-provider-commercetools as a tool for CT configurations. And I've faced this issue: 
**"commercetools_state.order_complete: expected roles.0 to be one of [ReviewIncludedInStatistics], got Return"**

**Comment by mvantellingen** [comment]
We auto-generate the go sdk based on the commercetools raml specification. I've just submitted a PR for adding this field to the specification. If that is merged we can regenerate the SDK and then it should work

**Comment by mvantellingen** [comment]
Fixed
