### ISSUE TITLE
add more topics/tags for better search this SDK

### ISSUE THREAD

**Issue by ashishhk** [labd/commercetools-go-sdk#71]
Hi, 
Can you please add more tags such as following, specially commercetools-sdk
![image](https://user-images.githubusercontent.com/4946943/148906136-9eb96192-ffb0-4014-b3f2-66fd6f03b664.png)

purpose is better search.

Regards
Ashish Dadhore
SDKs, Product Manager, commercetools

**Comment by mvantellingen** [comment]
Hi Ashish, I've added the `commercetools-sdk`topic
