### ISSUE TITLE
State Transitions empty/not set value is not respected due to omitempty annotation

### ISSUE THREAD

**Issue by etiennetremel** [labd/commercetools-go-sdk#72]
The following statement above the State resources Transitions field is not respected:

```
// Transitions are a way to describe possible transformations of the current state to other states of the same `type` (e.g.: _Initial_ -> _Shipped_).
// When performing a `transitionState` update action and `transitions` is set, the currently referenced state must have a transition to the new state.
// If `transitions` is an empty list, it means the current state is a final state and no further transitions are allowed.
// If `transitions` is not set, the validation is turned off.
// When performing a `transitionState` update action, any other state of the same `type` can be transitioned to.
Transitions []StateReference `json:"transitions,omitempty"`
```

When creating a State struct with empty Transitions then the Transition is not set while it should set an empty list.

I locally tried and was able to get it working by removing the `omitempty` from the Transitions field of both struct `State` and `StateDraft` in https://github.com/labd/commercetools-go-sdk/blob/main/platform/types_state.go#L10-L48, then it works as expected. Below is an example without the `omitempty` on the Transitions field:

```
type StateDraft struct {
	Key         string                    `json:"key"`
	Type        StateTypeEnum             `json:"type"`
	Name        *LocalizedString          `json:"name,omitempty"`
	Description *LocalizedString          `json:"description,omitempty"`
	Initial     *bool                     `json:"initial,omitempty"`
	Roles       []StateRoleEnum           `json:"roles,omitempty"`
	Transitions []StateResourceIdentifier `json:"transitions"`
}
```

Since these files are automatically generated, is there a way to override this specific setting?

Possibly related to the following issues:
- https://github.com/labd/terraform-provider-commercetools/pull/74
- https://github.com/labd/terraform-provider-commercetools/pull/122

**Comment by jenschude** [comment]
The `transitions` field is optional. So if they are omitted, they will not be set in the State. Question is way you need explicitly the field with an empty array?

**Comment by etiennetremel** [comment]
I agree, it's a little weird but It seems to be by design, this is what the [Commercetools documentation](https://docs.commercetools.com/api/projects/states#ctp:api:type:StateDraft) say about the Transitions field defined in States:

> **Set to empty list** for not allowing any transition from the current State and defining it as final State for a workflow.
> **Do not set this field at all** to turn off validation and allowing transitions to any other State of the same type as the current State.

When testing this behavior using Impex, I do see a difference in the object when defined as an empty list or not set.

**Comment by jenschude** [comment]
Just read up on the omitempty. This is indeed a problem as omitempty also drops zero length arrays. But even for optional fields this may not be intentional.

**Comment by jenschude** [comment]
Btw jettison has a flag omitnil which would leave the empty array intact: https://github.com/wI2L/jettison#improvements

**Comment by mvantellingen** [comment]
Ah jettison looks interesting. I'll see if we can move to that and use `omitnil` instead of `omitempty`. It might also solve the same issue in other locations

**Comment by jenschude** [comment]
But jettison has the risk of being a one person repository

**Comment by jenschude** [comment]
Is it possible to create a MarshallJson method for array types? Cause if you would have a MarshalJson for `[]StateResourceIdentifier` you could override the omitempty behavior.

**Comment by etiennetremel** [comment]
@mvantellingen @jenschude, anything I can help with?

**Comment by mvantellingen** [comment]
So in the currently generated SDK the following consderations are made:
 - Optional non-slice fields are always pointers and `omitempty` is added
 - Optional slice fields have `omitempty` added
 - Other fields have no `omitempty` tag

This results in the fact that slices which are empty are also omitted, while we want:
 - Nil slices to be omitted if optional, otherwise rendered as `null`
 - Empty slices always to be rendered as `[]`, either if this is optional or not

**Comment by mvantellingen** [comment]
I believe this should now be fixed. For optional array's we now remove the `omitempty` json tag so that they are always kept intact. The json output is then unmarshalled again to remove slices which are optional and nil and then marshalled again.

Downside of this approach is that we need an extra unmarshall/marshall step but I think the performance impact is minimal and this should be good enough for now
