### ISSUE TITLE
Introduce new version numbering

### ISSUE THREAD

**Issue by mvantellingen** [labd/commercetools-go-sdk#76]
Since we are auto generating the code based on RAML specifications of commercetools the version numbers don't really mean anything.

For the Python SDK we switched to calver, we might want to do the same for the Go SDK (although it's not really common in the Go ecosystem)

If we want to follow semver we have the following options:
 - v1.20221123.0 or v1.20220108.0
 - v2022.1123.0 or v2022.0108.0

**Comment by Multiply** [comment]
We've recently started using both the v0 and v1 sdk at the same time, and I would strongly suggest to keep semver as is (detached from CT versions), as the major part of the version indicates breaking changes between versions (in go code, ie. removed or changed types).

If you start generating the code differently, I'd expect a v2 to be released, so my project doesn't break between versions.

It should be enough to simply store the CT version in a var, or as part of the release description here in Github.
