### ISSUE TITLE
A Bug or an outdated README

### ISSUE THREAD

**Issue by circus-miguel** [labd/commercetools-go-sdk#77]
### Description
When I try to use the example in README ( master:latest ), I get several errors. <br>
- Edition-time: wrong & undefined types, and syntax errors. <br>
- Runtime: Panic
In the attached images, I've put the most relevant issues that I had. <br>

### Edition-time issues
![ct-bugs](https://user-images.githubusercontent.com/120652477/208948419-c8f79fd9-6e32-4fe5-ada8-d275c052b98a.png)

### Panic
After adapt the code, according the actually supported SDK, I'm having a panic() caused by nilness. <br>
The platform is panicking [here](https://github.com/labd/commercetools-go-sdk/blob/e7af4c1414e86cde2cab421956a23bcf5eadc03c/platform/client.go#L56)

![Screenshot 2022-12-21 at 16 43 08](https://user-images.githubusercontent.com/120652477/208951812-9c97611b-e526-4199-a1df-943b684ead1b.png)

And in order to avoid that, I must to init a specific attribute in the client, as illustrated above: <br>
The attribute that I initialize to make it work is `platform.ClientConfig.HTTPClient.Transport`. <br>
Otherwise it (the attribute ) ends nil when needed, triggering a panic().
![Screenshot 2022-12-21 at 16 44 27](https://user-images.githubusercontent.com/120652477/208951834-9dab5014-5647-4c04-8c6c-3c8f59bcb137.png)

### Environment
```console
$ go env
GO111MODULE=""
GOARCH="arm64"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by mvantellingen** [comment]
Thanks for the report. Both items are fixed. The client now fallsback to the default transport when no custom transport is defined and the example in the readme should work with the sdk
