### ISSUE TITLE
Outdated README published

### ISSUE THREAD

**Issue by circus-miguel** [labd/commercetools-go-sdk#78]
## Description
When I try to use the example in README ( master:latest ), I get some edition-time errors, all described in the attached image. I believe that's nothing more than the wrong version published.

### Additional related questions
1 - In order to use the package, I'm importing directly the published master. Is it the intended/recommended way?
2 - The [spew](github.com/davecgh/go-spew/spew) package is referenced in the README. Is that on purpose?

IDE error messages:
![ct-bugs](https://user-images.githubusercontent.com/120652477/210224977-baebc5dd-dd04-4117-8483-57a7190ef2b3.jpg)

**Comment by circus-miguel** [comment]
👋 
Any update on this issue?
I believe it's the same as in https://github.com/labd/commercetools-go-sdk/issues/77

**Comment by demeyerthom** [comment]
Hi @circus-miguel! Thanks for reaching out!

The README example is indeed faulty. I have created a pr here to update it: https://github.com/labd/commercetools-go-sdk/pull/85

With regards to your other questions:
- I am not 100% certain what you mean with "published master". I would recommend importing a tagged version of the SDK so you have no unexpected surprises when updating packages. So make sure your `go.mod` file includes the following require: `github.com/labd/commercetools-go-sdk v1.3.1`
- spew is just there to pretty-print the output of the API call. If you don't want that in your own code you can ignore that line/package
