### ISSUE TITLE
Panic when initializing the client without transport

### ISSUE THREAD

**Issue by papkos** [labd/commercetools-go-sdk#91]
There has been a version that would panic if provided with a custom `HTTPClient` with no `Transport`, but this has been fixed in https://github.com/labd/commercetools-go-sdk/commit/aa6fe6b17b760e62f343b233498e7712f5968ebb

We had a workaround while waiting for a new release with the above fix:
```go
client, err := platform.NewClient(&platform.ClientConfig{
	URL: cfg.CtBaseUrl,
	Credentials: &clientcredentials.Config{/* ... */},
	HTTPClient: &http.Client{
		Timeout: 30 * time.Second,
		// Need to provide a client that has a non-nil Transport, otherwise all requests fail with nil pointer dereference
		// Fixed in https://github.com/labd/commercetools-go-sdk/commit/aa6fe6b17b760e62f343b233498e7712f5968ebb
		// Waiting for new release
		Transport: http.DefaultTransport,
	},
})
```

Now a new release happened, which seems to revert to the panicking behavior: https://github.com/labd/commercetools-go-sdk/pull/88/files#diff-988b36dc49cd914d3fce440210c5522ad1ede4c33ff6565244c9cbe01ca64613

Is there a way/plan to make this long-term fixed?

**Comment by demeyerthom** [comment]
Hi @papkos thanks for reaching out

Hmm looks like this was a manual fix which got overwritten by the generator. I will see if I can fix the generator itself so it does not happen, and barring that change it manually again.
