### ISSUE TITLE
PredicateVar doesn't support slices

### ISSUE THREAD

**Issue by Multiply** [labd/commercetools-go-sdk#94]
https://github.com/labd/commercetools-go-sdk/blob/6167676b8af29d6b2c10e73f64505e43eec08743/platform/client_product_projections_by_project_key_product_projections_get.go#L97C4-L97C20

Is there a reason the following line is using `.Set` over `.Add`?

It's impossible to use slices of input when it overrides every time in the loop. It results in only the last value being sent to the API.

**Comment by Multiply** [comment]
Looking through more files, this seems to be the case for most, if not all occurrences of PredicateVar.

**Comment by mvantellingen** [comment]
Good question; the code is generated with rmf-codegen (we are the maintainer of the go part), see https://github.com/commercetools/rmf-codegen/blob/main/languages/go/src/main/kotlin/io/vrap/codegen/languages/go/client/MethodRenderer.kt#L153

**Comment by Multiply** [comment]
> Good question; the code is generated with rmf-codegen (we are the maintainer of the go part), see https://github.com/commercetools/rmf-codegen/blob/main/languages/go/src/main/kotlin/io/vrap/codegen/languages/go/client/MethodRenderer.kt#L153

From the looks of it, changing it to .Add shouldn't break any tests, right?

**Comment by demeyerthom** [comment]
@Multiply I opened a PR there to fix it: https://github.com/commercetools/rmf-codegen/pull/310. As soon as that gets merged I will update the sdk here and let you know!

**Comment by Multiply** [comment]
Thank you so much, @demeyerthom! 🚀

**Comment by Multiply** [comment]
Thanks for the swift fix!
